### ISSUE TITLE
UseCase3-TestCase SearchProduct

### ISSUE THREAD

**Issue by sinhaakanksha** [sinhaakanksha/SWE-project#2]
Bug in SearchProductUI- 

1. If no product is selected then on clicking **view card button** it shall not proceed to next UI. 
2. If _incorrect search query_ or search query padded with blank spaces is given, an alert message should be shown on the UI.
3. Initially when the cart is empty the **cart button** should be disabled for the customer.

TestCase author- @Sandeep-Das-og

**Comment by Sandeep-Das-og** [comment]
Bugs fixed in SearchProductUI -

1.) Initially when no product was selected and view card button was being clicked, it moved on the next UI. To fix this, error handling code has been added alongwith a _label_ to notify user to **Select an item first**.
2.) To fix the 2nd bug, the search query is now using _trim()_ method to remove leading/trailing blank spaces. Also, a label has been added to enhance the **search()** method.
3.) The **cart** has been _disabled_ if it is empty thereby preventing it to move onto the next UI.
